<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BOS-LAP-MDRASUL" ignored="0" name="Web Tech Widget Check Test" tests="1" failures="1" timestamp="07 Jul 2020 17:42:09 GMT" time="41.217" errors="0">
  <testcase name="webTectCheckSampleTest" time="37.048" classname="com.americanwell.autotest_web.techCheck.WebTechCheck_Test">
    <failure type="java.lang.AssertionError" message="Failed on Navigating to Mic widget by clicking Yes...  expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed on Navigating to Mic widget by clicking Yes...  expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.americanwell.autotest_web.techCheck.WebTechCheck_Test.webTectCheckSampleTest(WebTechCheck_Test.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- webTectCheckSampleTest -->
</testsuite> <!-- Web Tech Widget Check Test -->
